export const convos = [
    {
      topic: 'La La Land',
      author: 'henry',
      claps: 2,
      callins: 4,
      comments,
    },
    {
        topic: 'My friend',
        author: 'jill',
        claps: 6,
        callins: 2,
        comments,
      },
      {
        topic: 'Whatsup',
        author: 'mary',
        claps: 5,
        callins: 3,
        comments,
      },
      {
        topic: 'Heyyo',
        author: 'fred',
        claps: 7,
        callins: 7,
        comments,
      },
      {
        topic: 'Why Me?',
        author: 'bob',
        claps: 10,
        callins: 400,
        comments,
      },
      {
        topic: 'If Only',
        author: 'todd',
        claps: 82,
        callins: 40,
        comments,
      },
      {
        topic: 'Say Whhaaaa',
        author: 'angie',
        claps: 25,
        callins: 6,
        comments,
      },
      {
        topic: 'Mhmmm',
        author: 'sandy',
        claps: 20,
        callins: 9,
        comments,
      },
      {
        topic: 'Raaaaa',
        author: 'chris',
        claps: 28,
        callins: 43,
        comments,
      },
      {
        topic: 'Fwee',
        author: 'henry',
        claps: 21,
        callins: 42,
        comments,
      },
    ];